name: Build & Push (dev) to Artifact Registry

on:
  push:
    branches: ["development"]

permissions:
  contents: read
  id-token: write

env:
  PROJECT_ID: project-c5f72c1b-6454-456f-bc4
  GAR_LOCATION: europe-west1
  GAR_REPOSITORY: duman-platform

  SERVICE_NAME: gke-be-test-1

  WORKLOAD_IDENTITY_PROVIDER: projects/9788881395/locations/global/workloadIdentityPools/github-pool-1/providers/github-provider-1
  SERVICE_ACCOUNT: gke-test@project-c5f72c1b-6454-456f-bc4.iam.gserviceaccount.com

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - id: auth
        name: Authenticate to Google Cloud (WIF)
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ env.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ env.SERVICE_ACCOUNT }}

      - name: Docker login to Artifact Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.GAR_LOCATION }}-docker.pkg.dev
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.auth_token }}

      - name: Build & Push image (tag = SHA)
        run: |
          IMAGE="${GAR_LOCATION}-docker.pkg.dev/${PROJECT_ID}/${GAR_REPOSITORY}/dev/${SERVICE_NAME}"
          TAG="${IMAGE}:${GITHUB_SHA}"

          docker build -t "${TAG}" .
          docker push "${TAG}"

          echo "Pushed: ${TAG}"
